# Generated by Django 4.1 on 2022-12-25 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('semester', models.CharField(blank=True, choices=[('first', 'first semester'), ('second', 'second semester')], max_length=20, null=True)),
                ('grade', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
