# Generated by Django 4.1 on 2023-02-03 14:50

from django.db import migrations, models
import django.db.models.deletion
import school.cdn.backends
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('idealDuration', models.DurationField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني')], null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('classification', models.IntegerField(blank=True, choices=[(0, 'مادة علمية'), (1, 'مادة أدبية')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.answer')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('quiz.answer',),
        ),
        migrations.CreateModel(
            name='QuestionLevel',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.tag')),
            ],
            bases=('quiz.tag',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.tag')),
                ('dependencies', models.ManyToManyField(blank=True, to='quiz.skill')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
            bases=('quiz.tag',),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.answer')),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            bases=('quiz.answer',),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('question', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='quiz.tag'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AdminFinalAnswer',
            fields=[
                ('adminanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.adminanswer')),
            ],
            bases=('quiz.adminanswer',),
        ),
        migrations.CreateModel(
            name='AdminMultipleChoiceAnswer',
            fields=[
                ('adminanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.adminanswer')),
                ('image', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('quiz.adminanswer',),
        ),
        migrations.CreateModel(
            name='UserFinalAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.useranswer')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('quiz.useranswer',),
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.quiz')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            bases=('quiz.quiz',),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.userquiz'),
        ),
        migrations.CreateModel(
            name='SkillInst',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('skill', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.skill')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='quiz.skill'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.module')),
                ('skills', models.ManyToManyField(blank=True, to='quiz.skill')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSkill',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.tag')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
            bases=('quiz.tag',),
        ),
        migrations.CreateModel(
            name='AdminQuiz',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.quiz')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('questions', models.ManyToManyField(blank=True, to='quiz.question')),
            ],
            bases=('quiz.quiz',),
        ),
        migrations.CreateModel(
            name='UserMultipleChoiceAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.useranswer')),
                ('user_answer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.adminmultiplechoiceanswer')),
            ],
            bases=('quiz.useranswer',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('choices', models.ManyToManyField(blank=True, related_name='choices', to='quiz.adminmultiplechoiceanswer')),
                ('correct_answer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answer', to='quiz.adminmultiplechoiceanswer')),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='FinalAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('correct_answer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.adminfinalanswer')),
            ],
            bases=('quiz.question',),
        ),
    ]
