# Generated by Django 4.1 on 2022-12-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'first semester'), (2, 'second semester')], null=True),
        ),
    ]
