# Generated by Django 4.1 on 2022-12-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(0, 'scientific'), (1, 'literary')], null=True),
        ),
    ]
