# Generated by Django 4.1 on 2022-12-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_subject_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
