# Generated by Django 4.1 on 2022-12-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_quiz_quizanswer_questionanswer_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
