# Generated by Django 4.1 on 2022-12-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_question_category_remove_question_equations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
