# Generated by Django 4.1 on 2022-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email_alter_user_hashemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hashPhone',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
