# Generated by Django 4.1 on 2022-12-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='familyName',
            new_name='lastName',
        ),
    ]
