# Generated by Django 4.1 on 2022-12-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_familyname_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.IntegerField(blank=True, choices=[(0, 'العلمي'), (1, 'الأدبي'), (2, 'الصناعي')], null=True),
        ),
    ]
