# Generated by Django 4.1 on 2022-12-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('العلمي', 'العلمي'), ('الأدبي', 'الأدبي'), ('الصناعي', 'الصناعي')], max_length=50, null=True),
        ),
    ]
